# ===== Application =====
spring.application.name=factchecker

# ===== DataSource =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== OPEN_API_KEY =====
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini

# ===== Security Oauth ???  =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8081/realms/factchecker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://localhost:8081/realms/factchecker/protocol/openid-connect/certs